apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-cd-app-deployment
  labels:
    app: ci-cd-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ci-cd-app
  template:
    metadata:
      labels:
        app: ci-cd-app
    spec:
      containers:
      - name: ci-cd-app-container
        image: PLACEHOLDER_IMAGE_URL  # Jenkins replaces this with the actual image tag
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ci-cd-app-service
  labels:
    app: ci-cd-app
spec:
  type: LoadBalancer  # Change to NodePort or ClusterIP if needed
  selector:
    app: ci-cd-app
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
