# kubernetes-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-cd-app-deployment
  labels:
    app: ci-cd-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ci-cd-app
  template:
    metadata:
      labels:
        app: ci-cd-app
    spec:
      containers:
      - name: ci-cd-app-container
        # Placeholder: Jenkins will replace this with the built image tag
        image: PLACEHOLDER_IMAGE_URL
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ci-cd-app-service
spec:
  type: LoadBalancer # Use NodePort or ClusterIP if LoadBalancer isn't available
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: ci-cd-app