apiVersion: v1
kind: Service
metadata:
  name: ci-cd-app-service
  labels:
    app: ci-cd-app
spec:
  type: NodePort  # Change to LoadBalancer if your cluster supports it
  selector:
    app: ci-cd-app
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
