apiVersion: v1
kind: Service
metadata:
  name: cicd-demo-service
  labels:
    app: cicd-demo-app
spec:
  type: NodePort
  selector:
    app: cicd-demo-app
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
